language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: "5b9e4c3b-5136-488c-b148-cf26aab981fe"
  app: fridge-to-glass-cocktails
  skip_cleanup: true