language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: lSB9ynr12bVmzvHzkPLJCrT3IpqpFeiwu7ZPvd7XHTew1C3nwWT+nYQhNZex34tWtU+Iu/2Rwz/1Ewi0hVJmoC9TtnMfTys5SQcEuhCUYM5i5xpxEZ8Yr3q6Y3jjlFBkeo9xySRAO2EhPoNY/8V62YpuZCyn66ZC2TKfnwlp+08FFH2TZUBSCuZgaRStcKOjoVGsXt25UlSpBc43n/NfoJoFi2BCEjh1l4cK3IjAmJvQ+7E/YbDcb/pJREgsgnEamiMfKE3D4Wqcl8uB/N8c97ddsFVS/QcTSKCQLd7E69yhkN982O618szJQUyyz5i3IBLeONZPWGShuitkEp1ZqxMfiC35reTF6WRita6sAPxJIHhdO8lUDKvvcXZj5pZpAlA2LPwIRpDwxHkzT534lolzNX0Rijs5OXOY+baf4IjOSgQho5t9sxbY0j0nEP+DBgrh5pGhK9I5AFEc9HLROu42k9qKxM7kMpCQzh5OdxSof3vTg5zHd+hqAH2Ghtwph/qNArchJoVZYll3GSDwjJwOL48XRUvh6z3Ynd4JAGKzSFObhmIcJHV/mfSVpIGrupE7eEwBO170iBDeC0+azCBdjT2AhG/oKFJmX+WnGBWW7RsybYBfhcFJTiwHdpVn3MH89VbbXGIUA++Oeg01f0tYxOWvtjFguxQmsuxLL9Q=
  app: fridge-to-glass-cocktails
  skip_cleanup: true
